channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2024.3.11
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.9.19
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - anyio==4.3.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astropy==6.0.1
      - astropy-iers-data==0.2024.4.15.2.45.49
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - colorlover==0.3.0
      - comm==0.2.2
      - contourpy==1.2.1
      - cryodrgn==2.3.0
      - cufflinks==0.17.3
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.13.4
      - fonttools==4.51.0
      - fqdn==1.5.1
      - fsspec==2024.3.1
      - grpcio==1.62.1
      - h11==0.14.0
      - healpy==1.16.6
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.0
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.26.0
      - jupyterlab-widgets==1.1.7
      - kiwisolver==1.4.5
      - llvmlite==0.42.0
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.1.2
      - notebook-shim==0.2.4
      - numba==0.59.1
      - numpy==1.26.4
      - overrides==7.7.0
      - packaging==24.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==9.5.0
      - platformdirs==4.2.0
      - plotly==5.20.0
      - pluggy==1.4.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==5.26.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pyerfa==2.0.1.4
      - pygments==2.17.2
      - pynndescent==0.5.12
      - pyparsing==3.1.2
      - pytest
      - pytest-xdist
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.0
      - referencing==0.34.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.11.2
      - send2trash==1.8.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tenacity==8.2.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==2.2.2
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.2
      - widgetsnbextension==3.6.6
      - zipp==3.18.1
